### ISSUE TITLE
script.js error

### ISSUE THREAD

**Issue by RickHays** [multicolor-rgb/access-plugin-for-bludit#1]
I am getting this error in the console:
caught TypeError: Cannot read properties of null (reading 'dataset') at script.js:7:26

Not sure where the 'dataset' is coming from.  Have not found it yet, part of API? 

Works ok in Chrome, only reports the error.
In Firefox I see both Access Screen and Home Screen, accept button does not work
in Edge, it just does not work.

So not sure if its me or the plugin.
Also running Blundit 3.14.1

**Comment by multicolor-rgb** [comment]
Are you use this on root or subfolder localhost? You can share me www url i can check this? i test it ofc. Thanks for all!

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/access-plugin-for-bludit/archive/refs/heads/1.1.zip pleace check this version and give me any feedback

**Comment by RickHays** [comment]
I will test the 1.1 version, please contact me at rhays @ haysgang .com 
I will also make sure that the permissions are correct for my site using www-data.

**Comment by RickHays** [comment]
Your version 1.1 fixed the problem.  It now works in all 3 browsers.  Thank you for your help.

**Comment by RickHays** [comment]
I am sorry I spoke too soon, I get this error:

Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at script.js:6:26
(anonymous) @ script.js:6

When I set:  Show next time after accept? NO

If set to yes everything appears to work correctly.

**Comment by multicolor-rgb** [comment]
https://discord.gg/CdkZAyRX come to my discord and leave private message or leave all error on this place. I hope i can faster help you:) No problem, i do it a lot of plugins. I love help people:)

**Comment by multicolor-rgb** [comment]
fixed on 1.2
